### ISSUE TITLE
Releases on maven central?

### ISSUE THREAD

**Issue by dacrome** [hhandoko/cassandra-migration#26]
Hey,

thanks for this great project!
Is it possible to publish the releases on maven central or jcenter?

Greetz,
David

**Comment by hhandoko** [comment]
Hi @dacrome , I thought I did... First time publishing with Maven plugin 😁, will double check it. Thanks!

**Comment by hhandoko** [comment]
It seems that Sonatype OSS wasn't able to perform an automated release due to invalid PGP signature. I'll have to investigate this further.

In the meantime, you can use the Sonatype OSS `SNAPSHOT` repo:

https://oss.sonatype.org/content/repositories/snapshots/com/builtamont/cassandra-migration/

Don't forget to add the `SNAPSHOT` repo in your `pom.xml`:

``` xml
<repositories>
    <repository>
        <id>oss-sonatype</id>
        <name>oss-sonatype</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by hhandoko** [comment]
Hi @dacrome I've managed to correct the publishing of `cassandra-migration-0.9` onto Sonatype OSS repo. Please give it a few hours before it syncs to Maven Central.

**Comment by dacrome** [comment]
Wow @hhandoko that was fast! It's already on [maven central](http://search.maven.org/#artifactdetails%7Ccom.builtamont%7Ccassandra-migration%7C0.9%7Cjar). Thank you very much!
