### ISSUE TITLE
Feature - Allow to migrate several keyspaces

### ISSUE THREAD

**Issue by nmeln** [hhandoko/cassandra-migration#54]
From documentation it is not clear if migration of tables in several keyspaces is allowed. Is it possible?

## Outcome Desired

When `system` keyspace is passed in `KeyspaceConfiguration`, we should be able to apply migrations that use tables in different keyspaces.

<hr>

## Definition of Done

We can migrate tables in several keyspaces in one migration.

**Comment by hhandoko** [comment]
Hi @ranchoiver , can you elaborate, possibly with a specific example? e.g. Do you mean multiple keyspaces, each with a unique schema or multiple keyspaces with the same schema?

**Comment by hhandoko** [comment]
Hi @ranchoiver , have you had any thoughts about my comments above?

**Comment by nmeln** [comment]
Yes, I'll post an example use case tomorrow

On Apr 3, 2017 8:10 AM, "Herdy Handoko" <notifications@github.com> wrote:

Hi @ranchoiver <https://github.com/ranchoiver> , have you had any thoughts
about my comments above?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/builtamont-oss/cassandra-migration/issues/54#issuecomment-291049998>,
or mute the thread

**Comment by nmeln** [comment]
@hhandoko 
Sorry for the late response.

The use case is:
There are two (or more)  keyspaces, each with unique schema

- **keyspace  "aaa"**
   - table1
   - table2 

- **keyspace  "bbb"**
   - table3
   - table4

What if I want to change schema of **table1** and **table3** in the _same_ migration?
Is it possible?
Or should I create different migrations for each keyspace?

**Comment by hhandoko** [comment]
Hi @ranchoiver , IMO the simplest method is to use two different migrations since each keyspace has a unique schema. [Referring to the docs here](https://github.com/builtamont-oss/cassandra-migration/wiki/API-Migration), you can create two migrations and invoke them sequentially.

Is there a reason why you need to migrate several keyspaces in one migration as opposed to running a migration per each keyspace?

PS. I've just moved the docs into a Wiki format, so I can spend a bit of time to create some 'Use Cases' / examples section if that helps.
